import { createTamagui, createTokens } from '@tamagui/core';
import { color, size, space, radius, zIndex, outfitFont, interFont, spaceGroteskFont, dmSansFont, animations } from './tokens';

const tokens = createTokens({
  size,
  space,
  radius,
  zIndex,
  color,
});

const config = createTamagui({
  animations,
  defaultTheme: 'dark',
  shouldAddPrefersColorThemes: true,
  themeClassNameOnRoot: true,
  shorthands: {
    px: 'paddingHorizontal',
    py: 'paddingVertical',
    pt: 'paddingTop',
    pb: 'paddingBottom',
    pl: 'paddingLeft',
    pr: 'paddingRight',
    p: 'padding',
    mx: 'marginHorizontal',
    my: 'marginVertical',
    mt: 'marginTop',
    mb: 'marginBottom',
    ml: 'marginLeft',
    mr: 'marginRight',
    m: 'margin',
    bg: 'backgroundColor',
    f: 'flex',
    w: 'width',
    h: 'height',
    ai: 'alignItems',
    jc: 'justifyContent',
    fd: 'flexDirection',
    br: 'borderRadius',
    zi: 'zIndex',
  } as const,
  fonts: {
    heading: outfitFont,
    body: interFont,
    display: spaceGroteskFont,
    sans: dmSansFont,
  },
  tokens,
  themes: {
    dark: {
      background: tokens.color.background,
      surface: tokens.color.surface,
      primary: tokens.color.primary,
      secondary: tokens.color.secondary,
      text: tokens.color.text,
      textMuted: tokens.color.gray4,
      border: tokens.color.gray7,
      success: tokens.color.success,
      warning: tokens.color.warning,
      danger: tokens.color.danger,
      info: tokens.color.info,
    },
    light: {
      background: tokens.color.white,
      surface: tokens.color.gray1,
      primary: tokens.color.primary,
      secondary: tokens.color.secondary,
      text: tokens.color.gray9,
      textMuted: tokens.color.gray5,
      border: tokens.color.gray2,
      success: tokens.color.success,
      warning: tokens.color.warning,
      danger: tokens.color.danger,
      info: tokens.color.info,
    },
    cloudWhite: {
      background: tokens.color.cwBackground,
      surface: tokens.color.cwSurface,
      primary: tokens.color.cwPrimary,
      secondary: tokens.color.cwSecondary,
      text: tokens.color.cwForeground,
      textMuted: tokens.color.cwMutedForeground,
      border: tokens.color.cwBorder,
      success: tokens.color.cwSuccess,
      warning: tokens.color.warning,
      danger: tokens.color.cwDestructive,
      info: tokens.color.cwPrimary,
      foreground: tokens.color.cwForeground,
      card: tokens.color.cwCard,
      cardForeground: tokens.color.cwCardForeground,
      popover: tokens.color.cwPopover,
      popoverForeground: tokens.color.cwPopoverForeground,
      primaryForeground: tokens.color.cwPrimaryForeground,
      secondaryForeground: tokens.color.cwSecondaryForeground,
      muted: tokens.color.cwMuted,
      mutedForeground: tokens.color.cwMutedForeground,
      accent: tokens.color.cwAccent,
      accentForeground: tokens.color.cwAccentForeground,
      destructive: tokens.color.cwDestructive,
      destructiveForeground: tokens.color.cwDestructiveForeground,
      successForeground: tokens.color.cwSuccessForeground,
      borderStrong: tokens.color.cwBorderStrong,
      input: tokens.color.cwInput,
      ring: tokens.color.cwRing,
      sidebar: tokens.color.cwSidebar,
      sidebarForeground: tokens.color.cwSidebarForeground,
      sidebarPrimary: tokens.color.cwSidebarPrimary,
      sidebarPrimaryForeground: tokens.color.cwSidebarPrimaryForeground,
      sidebarAccent: tokens.color.cwSidebarAccent,
      sidebarAccentForeground: tokens.color.cwSidebarAccentForeground,
      sidebarBorder: tokens.color.cwSidebarBorder,
      sidebarRing: tokens.color.cwSidebarRing,
      gradientFrom: tokens.color.cwGradientFrom,
      gradientTo: tokens.color.cwGradientTo,
    },
  },
  media: {
    xs: { maxWidth: 660 },
    sm: { maxWidth: 800 },
    md: { maxWidth: 1024 },
    lg: { maxWidth: 1280 },
    xl: { maxWidth: 1560 },
  },
});

export type Conf = typeof config;

declare module '@tamagui/core' {
  interface TamaguiCustomConfig extends Conf {}
}

export default config;
